interface RestorationGuidanceCardProps {
  species?: any;
}

export default function RestorationGuidanceCard({
  species,
}: RestorationGuidanceCardProps) {
  const knowledge = species?.knowledge;

  if (!knowledge) {
    return (
      <section className="rounded-2xl border border-gray-200 bg-white p-8">
        <h2 className="text-3xl font-bold text-gray-900">
          🎯 Restoration Guidance
        </h2>

        <p className="mt-3 text-gray-600">
          Practical recommendations generated by FYNOS Intelligence.
        </p>

        <div className="mt-8 rounded-xl border border-gray-100 bg-gray-50 p-6 text-center">
          <p className="text-gray-500">
            No restoration guidance available.
          </p>
        </div>
      </section>
    );
  }

  return (
    <section className="rounded-2xl border border-gray-200 bg-white p-8">

      {/* =======================================================
          Header
      ======================================================= */}

      <div className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900">
          🎯 Restoration Guidance
        </h2>

        <p className="mt-3 text-gray-600">
          Recommended actions to maximize restoration success.
        </p>
      </div>

      {/* =======================================================
          Priority
      ======================================================= */}

      {knowledge?.priority && (
        <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-5">

          <p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">
            Restoration Priority
          </p>

          <p className="mt-2 text-lg font-semibold text-emerald-900">
            {knowledge.priority}
          </p>

        </div>
      )}

      {/* =======================================================
          Recommended Actions
      ======================================================= */}

      {knowledge?.recommended_actions?.length > 0 && (
        <div className="mt-8">

          <h3 className="mb-4 text-lg font-semibold text-gray-900">
            Recommended Actions
          </h3>

          <ul className="space-y-3">

            {knowledge.recommended_actions.map(
              (action: string, index: number) => (
                <li
                  key={index}
                  className="flex items-start gap-3"
                >
                  <span className="mt-1 text-emerald-600">
                    ✓
                  </span>

                  <span className="text-gray-700">
                    {action}
                  </span>
                </li>
              )
            )}

          </ul>

        </div>
      )}

    </section>
  );
}