import {
  Droplets,
  Trees,
  Sprout,
  Mountain,
  ShieldCheck,
  Sparkles,
  Lightbulb,
} from "lucide-react";

interface StepPrioritiesProps {
  priorities?: {
    title?: string;
    priorities?: {
      title?: string;
      reason?: string;
      description?: string;
    }[];
  };
}

const priorityIcons = [
  Droplets,
  Trees,
  Sprout,
  Mountain,
  ShieldCheck,
];

export default function StepPriorities({
  priorities,
}: StepPrioritiesProps) {
  const items = priorities?.priorities ?? [];

  return (
    <section className="space-y-10">
      {/* Header */}

      <div className="flex flex-col gap-8 lg:flex-row lg:items-start lg:justify-between">
        <div className="max-w-3xl">
          <p className="text-sm font-semibold uppercase tracking-[0.30em] text-emerald-600">
            Step 3 of 8
          </p>

          <h2 className="mt-4 text-5xl font-bold tracking-tight text-slate-900">
            Restoration priorities
          </h2>

          <p className="mt-6 text-lg leading-8 text-slate-600">
            Based on your landscape diagnosis, these are the first restoration
            priorities identified by FYNOS AI.
          </p>
        </div>

        <div className="max-w-md rounded-3xl border border-emerald-100 bg-white p-6 shadow-sm">
          <div className="flex items-start gap-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-amber-50">
              <Sparkles
                className="h-5 w-5 text-amber-500"
                strokeWidth={2}
              />
            </div>

            <p className="text-base leading-7 text-slate-600">
              These priorities are generated by{" "}
              <span className="font-semibold text-emerald-700">
                FYNOS AI
              </span>{" "}
              using satellite analysis, ecological intelligence, and
              restoration science.
            </p>
          </div>
        </div>
      </div>

      {/* Priority cards */}

      <div className="space-y-5">
        {items.map((priority, index) => {
          const Icon = priorityIcons[index] ?? Sprout;

          return (
            <div
              key={index}
              className="rounded-3xl border border-emerald-100 bg-white shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:shadow-md"
            >
              <div className="grid gap-8 p-8 lg:grid-cols-[1.15fr_1fr_1fr]">
                {/* Priority */}

                <div className="flex items-start gap-5">
                  <div className="flex h-16 w-16 flex-shrink-0 items-center justify-center rounded-full bg-emerald-50 ring-1 ring-emerald-100">
                    <Icon
                      className="h-8 w-8 text-emerald-600"
                      strokeWidth={2}
                    />
                  </div>

                  <div>
                    <h3 className="text-3xl font-bold leading-tight tracking-tight text-slate-900">
                      {priority.title}
                    </h3>
                  </div>
                </div>

                {/* Why */}

                <div className="border-l border-slate-200 pl-8">
                  <p className="text-sm font-semibold text-emerald-700">
                    Why FYNOS AI recommends this
                  </p>

                  {priority.reason && (
                    <p className="mt-4 text-base leading-7 text-slate-600">
                      {priority.reason}
                    </p>
                  )}
                </div>

                {/* Action */}

                <div className="border-l border-slate-200 pl-8">
                  <p className="text-sm font-semibold text-emerald-700">
                    Recommended action
                  </p>

                  {priority.description && (
                    <p className="mt-4 text-base leading-7 text-slate-600">
                      {priority.description}
                    </p>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Footer */}

      <div className="rounded-3xl border border-emerald-100 bg-emerald-50 p-6">
        <div className="flex items-start gap-4">
          <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-white shadow-sm">
            <Lightbulb
              className="h-5 w-5 text-amber-500"
              strokeWidth={2}
            />
          </div>

          <div>
            <p className="font-semibold text-slate-900">
              Good to know
            </p>

            <p className="mt-2 leading-7 text-slate-600">
              These priorities represent the best starting points for your
              restoration journey. You'll explore each recommendation in
              more detail throughout the next steps.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}