import React from "react";

interface StepLocationProps {
  country: string;
  setCountry: React.Dispatch<React.SetStateAction<string>>;

  region: string;
  setRegion: React.Dispatch<React.SetStateAction<string>>;

  province: string;
  setProvince: React.Dispatch<React.SetStateAction<string>>;

  community: string;
  setCommunity: React.Dispatch<React.SetStateAction<string>>;
}

export default function StepLocation({
  country,
  setCountry,
  region,
  setRegion,
  province,
  setProvince,
  community,
  setCommunity,
}: StepLocationProps) {
  return (
    <div className="mt-6">
      <label className="text-xl font-semibold text-gray-900">
        🌎 Where is the land you'd like to restore?
      </label>

      {/* Country */}
      <select
        value={country}
        onChange={(e) => setCountry(e.target.value)}
        className="mt-3 w-full rounded-lg border border-emerald-200 px-4 py-3 focus:outline-none focus:ring-2 focus:ring-emerald-500"
      >
        <option value="">Select a country</option>
        <option value="Peru">Peru</option>
        <option value="Brazil">Brazil</option>
        <option value="Colombia">Colombia</option>
        <option value="Ecuador">Ecuador</option>
        <option value="Bolivia">Bolivia</option>
      </select>

      {/* Region */}
      {country && (
        <div className="mt-4">
          <label className="block mb-2 font-medium text-gray-700">
            Region / State
          </label>

          <input
            type="text"
            value={region}
            onChange={(e) => setRegion(e.target.value)}
            placeholder="Example: Ucayali"
            className="w-full rounded-lg border border-emerald-200 px-4 py-3 focus:outline-none focus:ring-2 focus:ring-emerald-500"
          />
        </div>
      )}

      {/* Province */}
      {region && (
        <div className="mt-4">
          <label className="block mb-2 font-medium text-gray-700">
            Province
          </label>

          <input
            type="text"
            value={province}
            onChange={(e) => setProvince(e.target.value)}
            placeholder="Example: Coronel Portillo"
            className="w-full rounded-lg border border-emerald-200 px-4 py-3 focus:outline-none focus:ring-2 focus:ring-emerald-500"
          />
        </div>
      )}

      {/* Community */}
      {province && (
        <div className="mt-4">
          <label className="block mb-2 font-medium text-gray-700">
            Community
          </label>

          <input
            type="text"
            value={community}
            onChange={(e) => setCommunity(e.target.value)}
            placeholder="Example: Yamino"
            className="w-full rounded-lg border border-emerald-200 px-4 py-3 focus:outline-none focus:ring-2 focus:ring-emerald-500"
          />
        </div>
      )}

      {/* AI placeholder */}
      {region && (
        <div className="mt-6 rounded-xl border border-emerald-100 bg-emerald-50 p-4">
          <p className="text-gray-700">
            Wonderful.
          </p>

          <p className="mt-2 text-gray-700">
            <span className="font-semibold text-emerald-700">{region}</span>{" "}
            sounds like an interesting place to restore.
          </p>

          <p className="mt-2 text-sm text-gray-500 italic">
            (Soon this message will be generated by FYNOS AI.)
          </p>
        </div>
      )}
    </div>
  );
}